<?php

/** @var $block \Magento\Framework\View\Element\Template */

$block = \Magento\Framework\App\ObjectManager::getInstance()->get('Perspective\CurrentProdCat\Block\Index');


// print current product data
if ($currentProduct = $block->getCurrentProduct()) {
    echo $currentProduct->getName() . '<br />';
    echo $currentProduct->getSku() . '<br />';
    echo $currentProduct->getFinalPrice() . '<br />';
    echo $currentProduct->getProductUrl() . '<br />';
    print_r($currentProduct->getCategoryIds()) . '<br />';
}
// print current category data
if ($currentCategory = $block->getCurrentCategory()) {
    echo $currentCategory->getName() . '<br />';
    echo $currentCategory->getUrl() . '<br />';
}
