<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /** @var $block \Magento\Framework\Pricing\Render\Amount */ ?>

<span class="price-container <?= $block->escapeHtmlAttr($block->getAdjustmentCssClasses()) ?>" <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
  <?php if ($block->getDisplayLabel()) : ?>

    <!-- 2.5 Добавить слово “Price:” перед элементом 5. Должно выглядеть так: “Price: $77“ -->

    <span class="price-label"><?= $block->escapeHtml($block->getDisplayLabel()) . '<br/>(2.5) Price ' ?></span>
  <?php endif; ?>
  <span <?php if ($block->getPriceId()) : ?> id="<?= $block->escapeHtmlAttr($block->getPriceId()) ?>" <?php endif; ?> <?= ($block->getPriceDisplayLabel()) ? 'data-label="' . $block->escapeHtmlAttr($block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes()) . '"' : '' ?> data-price-amount="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>" data-price-type="<?= $block->escapeHtmlAttr($block->getPriceType()) ?>" class="price-wrapper <?= $block->escapeHtmlAttr($block->getPriceWrapperCss()) ?>"><?= $block->escapeHtml($block->formatCurrency($block->getDisplayValue(), (bool)$block->getIncludeContainer()), ['span']) ?></span>
  <?php if ($block->hasAdjustmentsHtml()) : ?>
    <?= $block->getAdjustmentsHtml()  ?>
  <?php endif; ?>
  <?php if ($block->getSchema()) : ?>
    <meta itemprop="price" content="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>" />
    <meta itemprop="priceCurrency" content="<?= $block->escapeHtmlAttr($block->getDisplayCurrencyCode()) ?>" />
  <?php endif; ?>
</span>