<?php

/** @var ViewModel */

use TestTasks\Timer\ViewModel\ViewModel;

?>
<?php $viewModel = $this->getData('view_model'); ?>

<?php if ($viewModel->isSimpleProduct()) : ?>
    <?php if ($viewModel->getRulePriceEnd() !== null || $viewModel->getSpecialPriceEnd() !== null) : ?>
        <h2>
            <div id="getting-started"></div>
            <script type="text/javascript">
                require([
                    'jquery',
                    'countdown'
                ], function(
                    $, countdown
                ) {
                    jQuery("#getting-started")
                        .countdown("<?= $viewModel->getSmallestDate() ?>", function(event) {
                            jQuery(this).text(
                                event.strftime('%D Days %H Hours %M Minutes %S Seconds')
                            );
                        });
                });
            </script>
        </h2>
        <h3> <?= 'Special Price End Date   -   ' . $viewModel->getSpecialPriceEnd() ?></h3>
    <?php endif ?>



    <?php if (!$viewModel->getRulesNames() == null) : ?>
        <?php foreach ($viewModel->getRulesNames() as $name) : ?>
            <h3> <?= $name['name'] . '  -  ' . $name['date'] ?> </h3>
        <?php endforeach ?>
    <?php endif ?>
<?php endif ?>
