<?php

$productId = 20; // YOUR PRODUCT ID
$product = $block->getProductById($productId);

// for current product
// $product = $block->getCurrentProduct();

$categoryIds = $product->getCategoryIds();


// $block->getCategoryCollection() (получаем коллекцию всех категорий) ->addAttributeToFilter('entity_id', $categoryIds); (фильтруем, первый параметр - указывает сортировку по айди категории, второй массив айди категорий из продукта) 
// В $categories получаем нужные категории. Foreach перебираем и выводим имя категории.

$categories = $block->getCategoryCollection()
    ->addAttributeToFilter('entity_id', $categoryIds);

foreach ($categories as $category) {
    echo $category->getName() . '<br>';
}
