<?php

/** @var \Perspective\BDPractice\Block\Index $block */ ?>
<?php $post = $block->getPostCollectionForProduct(); ?>
<table border="1">
  <tr>
    <td>Id</td>
    <td>Category id</td>
    <td>Product id</td>
    <td>Review text</td>
    <td>Created at</td>
    <td>Customer name</td>
    <td>Customer email</td>
  </tr>
  <?php
  foreach ($post as $elem) : ?>
    <tr>
      <td><?= $elem->getData('ID') ?></td>
      <td><?= $elem->getData('IDCat') ?></td>
      <td><?= $elem->getData('IDProd') ?></td>
      <td><?= $elem->getData('TextRev') ?></td>
      <td><?= $elem->getData('DataRev') ?></td>
      <td><?= $elem->getData('Name') ?></td>
      <td><?= $elem->getData('Email') ?></td>
    </tr>
  <?php endforeach; ?>
</table>