<?php

/** @var \Perspective\BDPractice\Block\Category $block */ ?>
<?php $post = $block->getPostCollectionForCategory(); ?>

<table border="1">
  <tr>
    <td>Revocation id</td>
    <td>ID product categories</td>
    <td>Product id</td>
    <td>Product sku</td>
    <td>Product name</td>
    <td>Product price</td>
    <td>Product image</td>
    <td>Review text</td>
    <td>Date and time of publication</td>
    <td>Customer name</td>
    <td>Customer email</td>
  </tr>
  <?php
  foreach ($post as $elem) : ?>
    <tr>
      <td><?= $elem->getData('ID') ?></td>
      <td><?= $elem->getData('IDCat') ?></td>
      <td><?= $elem->getData('IDProd') ?></td>
      <td><?php $product = $block->getProductById($elem->getData('IDProd')) ?>
        <?= $product->getSku() ?></td>
      <td><?= $product->getName() ?></td>
      <td><?= $product->getPrice() ?></td>
      <td><img src="<?= $block->getProductImageUrl($product, 'product_small_image') ?>"></td>
      <td><?= $elem->getData('TextRev') ?></td>
      <td><?= $elem->getData('DataRev') ?></td>
      <td><?= $elem->getData('Name') ?></td>
      <td><?= $elem->getData('Email') ?></td>
    </tr>
  <?php endforeach; ?>
</table>