<?php
$ids = [4, 5, 6];
$categoryProducts = $block->getProductCollectionByCategories($ids); ?>
<?php if (!is_null($categoryProducts))  ?>
<ul class="category-products">
    <?php
    foreach ($categoryProducts  as $product) : ?>
        <li class="level0-child">
            <a href="<?php echo $product->getProductUrl(); ?>">
                <?php echo $product->getName(); ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>