<?php $orders = $block->getCustomerOrder();
foreach ($orders as $order) {
    echo '<b>entity_id -</b> ' . $order['entity_id'] . "<br/>";
    echo '<b>customer_id - </b>' . $order['customer_id'] . "<br/>";
    echo '<b>customer_name - </b>' . $order['customer_firstname'] . ' ' . $order['customer_lastname'] . "<br/>";
    echo '<b>status - </b>' . $order['status'] . "<br/>";
    echo '<b>grand_total -</b> ' . $order['grand_total'] . "<br/>";
    echo '<b>created_at -</b> ' . $order['created_at'] . "<br/>";
    echo "<hr/>";
}
