<?php
$ids = [23];
$collection = $block->getData('view_model')->getProductCollectionByCategories($ids);
?>

<p> <?php echo $block->getData('view_model')->show($collection); ?></p>


<h2>Продукты из категории Women - Tops - Jackets, где цена от 50$ до 60$</h2>
<table border="1px">
    <th>Name</th>
    <th>Sku</th>
    <th>Price</th>
    <p><?php echo $block->getData('view_model')->showTable($collection); ?></p>
</table>